"""One-off generator for the lamp shade mesh -- MuJoCo has no native truncated-cone
(frustum) primitive, so this writes a plain OBJ (open top and bottom, side wall
only, so the hollow interior/bulb is visible from an angle) that the MJCF
references as a <mesh>. Not part of the runtime package; run once, commit the
output.

Axis: mesh-local +Z. Narrow end (attaches to the neck) at z=0, wide end (light
opening) at z=+height.
"""

from __future__ import annotations

import math
from pathlib import Path

OUT_PATH = Path(__file__).parent.parent / "assets" / "so_arm100" / "assets" / "lamp_shade.obj"

TOP_RADIUS = 0.015  # narrow end, at the neck attachment (30mm diameter)
BOTTOM_RADIUS = 0.0275  # wide end, the light opening (55mm diameter)
HEIGHT = 0.060
SIDES = 24


def generate() -> str:
    lines = ["# lamp shade frustum, generated by scripts/gen_lamp_shade_mesh.py"]
    top_ring = []
    bottom_ring = []
    for i in range(SIDES):
        angle = 2 * math.pi * i / SIDES
        cos_a, sin_a = math.cos(angle), math.sin(angle)
        top_ring.append((TOP_RADIUS * cos_a, TOP_RADIUS * sin_a, 0.0))
        bottom_ring.append((BOTTOM_RADIUS * cos_a, BOTTOM_RADIUS * sin_a, HEIGHT))

    for x, y, z in top_ring + bottom_ring:
        lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")

    # Side wall as quads (two triangles each), 1-indexed per OBJ convention.
    for i in range(SIDES):
        j = (i + 1) % SIDES
        t0, t1 = i + 1, j + 1
        b0, b1 = SIDES + i + 1, SIDES + j + 1
        lines.append(f"f {t0} {b0} {b1}")
        lines.append(f"f {t0} {b1} {t1}")

    return "\n".join(lines) + "\n"


def main() -> None:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(generate())
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
